// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdYD3pXSUfQPiRr8aPlostPGlXrnuDjc',
    appId: '1:611152986851:web:f8ee871bf434d729213bd6',
    messagingSenderId: '611152986851',
    projectId: 'islamhub-f7b80',
    authDomain: 'islamhub-f7b80.firebaseapp.com',
    storageBucket: 'islamhub-f7b80.appspot.com',
    measurementId: 'G-0LND5VQNBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIHeEr1OQ9zH3rWTSdGtfyYPNUEwEvfS4',
    appId: '1:611152986851:android:038affc4d836bfa4213bd6',
    messagingSenderId: '611152986851',
    projectId: 'islamhub-f7b80',
    storageBucket: 'islamhub-f7b80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRPC-1vyKj92hQOVaqK2_jqsaQ6denoo',
    appId: '1:611152986851:ios:79b10f3b7a8aa1a4213bd6',
    messagingSenderId: '611152986851',
    projectId: 'islamhub-f7b80',
    storageBucket: 'islamhub-f7b80.appspot.com',
    iosBundleId: 'com.example.islamversehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYRPC-1vyKj92hQOVaqK2_jqsaQ6denoo',
    appId: '1:611152986851:ios:569435b35968ea7b213bd6',
    messagingSenderId: '611152986851',
    projectId: 'islamhub-f7b80',
    storageBucket: 'islamhub-f7b80.appspot.com',
    iosBundleId: 'com.example.islamversehub.RunnerTests',
  );
}
